name: PHPUnit

on:
  push:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:

  tests:
    name: Tests (PHP ${{ matrix.php }} on ${{ matrix.operating-system }})
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.php == '8.2' }}

    strategy:
      fail-fast: false
      matrix:
        operating-system: ['ubuntu-latest']
        php: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install PHP with latest composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=-1, display_errors=On, log_errors_max_len=0
          coverage: none
          tools: none

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-composer-dependencies
      - name: "Install Composer dependencies (PHP < 7.3)"
        if: ${{ matrix.php < '7.3' }}
        uses: "ramsey/composer-install@v2"
        with:
          composer-options: --prefer-lowest

      - name: "Install Composer dependencies (PHP < 8.2)"
        if: ${{ matrix.php >= '7.3' && matrix.php < '8.2' }}
        uses: "ramsey/composer-install@v2"

      - name: "Install Composer dependencies (PHP 8.2)"
        if: ${{ matrix.php >= '8.2' }}
        uses: "ramsey/composer-install@v2"
        with:
          composer-options: --ignore-platform-reqs

      - name: Run tests
        run: vendor/bin/phpunit --coverage-text
